# $Id: makefile,v 1.3 2001/05/21 17:36:42 phaller Exp $

#
# EnvEd
#
# History:
#
# $Log: makefile,v $
# Revision 1.3  2001/05/21 17:36:42  phaller
# Added fake makefile to prevent stop in build process
#
# Revision 1.2  2001/03/01 16:08:34  phaller
# .
#
# Revision 1.1  2001/02/28 18:08:30  phaller
# Added all sub-makefiles
#
#
#
#

#
# Set the target
#


nop:


all: nop

lib: nop

dep: nop

install: nop
