/*****************************************************************************
 * Projekt   : PHS CPVersion
 * Name      : Modul CPVersion
 * Funktion  : Hauptmodul
 * Parameter :
 * Variablen :
 * Ergebnis  :
 * Bemerkung :
 *
 * Autor     : Patrick Haller [Dienstag, 05.09.1995 22.50.30]
 *****************************************************************************/

#ifndef MODULE_CPVERSION
#define MODULE_CPVERSION


/*****************************************************************************
 * Includes                                                                  *
 *****************************************************************************/



#endif /* MODULE_CPVERSION */
