# $Id: makefile,v 1.1 2002/09/28 03:35:55 bird Exp $

#
# CHKPath
#

#
# Setup config.
#
PATH_ROOT       = ..\..
!include $(PATH_ROOT)\make\setup.mak


#
# Target config.
#
TARGET_NAME     = autochkdsk

TARGET_LIBS     = \
$(LIB_OS) \
$(LIB_C_OBJ) \



#
# Rules config.
#
!include $(MAKE_INCLUDE_PROCESS)

